### ISSUE TITLE
Flaky  tests

### ISSUE THREAD

**Issue by StummeJ** [FelschR/AspNetCore.Identity.DocumentDB#15]
I noticed that the tests seem to have a timing issue.  We saw this in one of our projects on CI but not our machines when testing with DocumentDB Emulator.  For us forcing the test runner onto a single thread allowed it to finish the tests in an exponentially quicker timeframe.

Cheers

**Comment by FelschR** [comment]
I'll mark this as done now as this should be fixed within #17.
The Integration Tests now run sequentially and don't interfere with each other.
The other Tests can still run in parallel but as far as I can see they shouldn't cause any interferences.
