### ISSUE TITLE
Dependency on Nuget.CommandLine

### ISSUE THREAD

**Issue by trailmax** [FelschR/AspNetCore.Identity.DocumentDB#22]
Hi,

I've almost installed your NuGet package, but noticed that there is `NuGet.CommandLine` package that is pulled in as well. But quick look through code did not reveal any need for that. 
As far as I can see this requirement comes from [this line](https://github.com/FelschR/AspNetCore.Identity.DocumentDB/blob/netcore/src/AspNetCore.Identity.DocumentDB/project.json#L37)

Is there a reason to have this dependency? Can this be removed?

Thanks!
Max

**Comment by FelschR** [comment]
Yes, I fixed that in 8aca2b96ffc733734c1ec4437b392a15d0d2d3b4 but it seems I haven't done a NuGet release since then.

**Comment by FelschR** [comment]
Ok, I've had some issues with my updates build script (was only working on my development branch).
But they are all resolved now and a new build 0.3.5-beta is up on NuGet.

**Comment by trailmax** [comment]
Awesome, thank you!
