### ISSUE TITLE
Included it in my AspNetCore 2.0 Applicaiton

### ISSUE THREAD

**Issue by benzmarkus** [FelschR/AspNetCore.Identity.DocumentDB#28]
Hi,

i did not find any class even the namespace is not available. In the Object-Browser everything is empty.
Using Nuget V3.

Kind Regards
Markus

**Comment by FelschR** [comment]
The IdentityUser & IdentityRole classes are available in the `Microsoft.AspNetCore.Identity.DocumentDB` namespace.

And the AddIdentityWithDocumentDBStores & RegisterDocumentDBStores methods are extensions in the `Microsoft.Extensions.DependencyInjection` namespace.

I've tried to replicate this issue but I was able to successfully use the latest version of the library via NuGet (in Visual Studio 2017).

Can you perhaps give me a little more information on your setup? Are you trying to use it directly in an netcoreapp2.0 project or a netstandard2.0 library? Which Visual Studio & NuGet versions do you use?

**Comment by FelschR** [comment]
@benzmarkus If you managed to get it working could you confirm it, please?

**Comment by benzmarkus** [comment]
Can try it today. Wanted to do it earlier

Felix Schröter <notifications@github.com> schrieb am Mo., 26. Feb. 2018
11:08:

**Comment by benzmarkus** [comment]
Hi,

i found the classes but the example in the repository is a little bit old. 

Kind Regards
Markus

**Comment by FelschR** [comment]
Glad to hear you could solve the issue.

The `services.AddIdentityWithDocumentDBStores(documentClient, databaseLink);` example should still work.

But I admit the documentation is missing the alternative methods and could be a lot more detailed.

**Comment by benzmarkus** [comment]
Can you create a working example with core2.0?

Felix Schröter <notifications@github.com> schrieb am Do., 1. März 2018
15:27:

**Comment by FelschR** [comment]
I've added a sample project that has already set credentials for using the local Cosmos DB Emulator.
It can be used with netcoreapp1.0 & netcoreapp2.0 (see conditional packages in .csproj & #if section in Startup.cs).

There is POST Controller that takes a username as route argument to test if it's working.
I think otherwise the code should be quite self-explanatory.

If you have any questions go ahead and ask :)

**Comment by benzmarkus** [comment]
last commit was sep 2017 ... did you push your commit ?

**Comment by benzmarkus** [comment]
ok found it

**Comment by FelschR** [comment]
I'm preparing to release v1.0.0 now.
All that was missing the whole time was some proper documentation. I've added that now and will push v1 to NuGet soon.

**Comment by FelschR** [comment]
I'm closing this issue now. Please comment or reopen a new issue if you're still experiencing problems.
