### ISSUE TITLE
Support camelCase property names

### ISSUE THREAD

**Issue by dominikfoldi** [FelschR/AspNetCore.Identity.DocumentDB#32]
What was the motivation behind using PascalCase for property names in JSON? As I can see, the standard for NoSQL databases is camelCase.

We would like to use camelCase conventions for every model in our database, but it would not be so nice to mix the two conventions.

Thank you.

**Comment by FelschR** [comment]
Since 2.0.0beta the library is using camelCase now.
There is no automatic migration, so the 2.0 releases are not backwards compatible, though.
