### ISSUE TITLE
While retreiving users I get 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by vindemi** [FelschR/AspNetCore.Identity.DocumentDB#36]
`_userManager.Users.AsEnumerable();`

The line above gives me an error. I use this option:

`services.AddIdentity<IdentityUser, IdentityRole>()
                .RegisterDocumentDBStores<IdentityUser, IdentityRole>(client, (p) => new DocumentCollection { Id = "userCollection" });`

And what exactly is **databaselink** property ?

**Comment by FelschR** [comment]
Hi @vindemi,

which version are you using?
For 2.0.0-beta & 2.0.0-beta2 I'm currently focusing on the support of partitioned collections.
There might be an issue with normal collections.
Also if you are on the older beta release try updating to the newer one.

In case you want to use it with partitioning you should provide the partition key definition in the DocumentCollection.
At the moment the beta only allows you to set "/partition" as the key but I'll try to make that configurable in a later version. If you set the definition to a value other than "/partition" that will cause issues.

**Comment by vindemi** [comment]
Thanks for the reply @FelschR 
Indeed. I was confused on the readme's information by following it and I wanted to use `services.AddIdentity<IdentityUser, IdentityRole>()
		.RegisterDocumentDBStores<IdentityUser, IdentityRole>(documentClient, databaseLink);` line.
But didn't know what is the databaseLink property (and I fought that's the issue). But the problem was that CosmosDB itself doesn't support retreiving collection from _userManager.Users property (some linq issue). Sorry for the inconvenience.

**Comment by FelschR** [comment]
The `userManager.Users` property should usually be accessible.
