### ISSUE TITLE
Use `IDocumentClient` instead of `DocumentClient`

### ISSUE THREAD

**Issue by rhalaly** [FelschR/AspNetCore.Identity.DocumentDB#45]
Using `DocumentClient` in `RegisterDocumentDBStores` instead of `IDocumentClient` prevents to use mocks of `IDocumentClient` with this library.

Changing the interface to `IDocumentClient` can help a lot.

**Comment by FelschR** [comment]
Very good point!

**Comment by rhalaly** [comment]
Thank you for your quick support :)
