### ISSUE TITLE
Create sample project

### ISSUE THREAD

**Issue by FelschR** [FelschR/AspNetCore.Identity.DocumentDB#5]
Create a sample project.

**Comment by FelschR** [comment]
Maybe this could be used as base:
https://github.com/g0t4/aspnet-identity-mongo-sample

**Comment by FelschR** [comment]
Better would be just to use the default ASP.NET (Web API) project template provided by Visual Studio and add code with Controller samples using the userManager (register, login, etc.).

**Comment by murrayLuke** [comment]
If you could get this going with the Web API project I would greatly appreciate it, I've been trying for the past day and haven't quite figured out how to do it.

**Comment by FelschR** [comment]
Basically you only need to register it in the Startup.cs in the ConfigureServices method in one of the two ways:

Variant 1 registers both the ASP.NET Identity and DocumentDB provider in one method call.
No need to manually call services.AddIdentity() before.
```csharp
services.AddIdentityWithDocumentDBStores<Model.UserIdentity, Microsoft.AspNetCore.Identity.DocumentDB.IdentityRole>(client, databaseService.Database.SelfLink);
```

Variant 2 register the ASP.NET Identity and DocumentDB provider separately:
```csharp
var client = new DocumentClient(uri, authToken);
var db = await client.CreateDatabaseIfNotExistsAsync(new Microsoft.Azure.Documents.Database { Id = databaseId });
var usersCollection = await Client.CreateDocumentCollectionIfNotExistsAsync(Database.SelfLink, new DocumentCollection { Id = collectionId });

services
    .AddIdentity<UserIdentity, RoleIdentity>() // or your custom code
    .RegisterDocumentDBStores<UserIdentity, RoleIdentity>(client, db.SelfLink);
```

UserIdentity & RoleIdentity are your own custom classes that extend IdentityUser & IdentityRole. But you can also use the uncostumized IdentityUser & IdentityRole from DocumentDB SDK directly.

And inject it in the Controllers where you want to use it like this:

```csharp
// Controller constructor
// make sure UserIdentity and RoleIdentity used here are the same as used for registering the services.
public TestController(UserManager<UserIdentity> userManager, SignInManager<RoleIdentity> signInManager)
{
    // do whatever you want with the userManager & signInManager
}
```

Hopefully this will already help you.
Let me know if it works.

**Comment by FelschR** [comment]
added in 27d1fe0dfecf98e100ab133b4fc3d872df09c0db
