### ISSUE TITLE
Control Id

### ISSUE THREAD

**Issue by javaadpatel** [FelschR/AspNetCore.Identity.DocumentDB#51]
Hi,

Firstly, thanks for the awesome library. I am getting started with it and was wondering if there is a way to set the id of the inserted document? The id's are being set automatically like below:
![image](https://user-images.githubusercontent.com/22832462/58477614-3ea8da00-8154-11e9-94a0-bd6d6a138ece.png)

**Comment by FelschR** [comment]
When using partitioning the `id` field values are not configurable at the moment.

**Comment by javaadpatel** [comment]
okay that is understandable, i read that you are currently busy with implementing the partioning where i'd be able to set my own partitionkey, when that is complete would that also allow setting the id field?

With the current implementation, what would be the best way to query for a specific user if there were a significant amount of users stored (say 1 million)? Since the partitionkey is auto-generated i couldn't use that, so would i have to use something like usermanager.FindByEmailAsync? and how slow would that be?

**Comment by javaadpatel** [comment]
Alternatively,
Would it be possible to override the FindbyIdAsync method? Then I could search for a custom property and have that property be indexed as well?

**Comment by FelschR** [comment]
Actually I haven't found much time for those enhancements.

When using partitioning the partition key will be the user id. This means you can use your own value by setting the `Id` property of the identity user.

The methods `FindByEmailAsync` & `FindByNameAsync` use mapping DB entries. This means when they're called there will be 2 DB requests which is certainly slower than using `FindByIdAsync` but it's way more efficient than querying the user documents by email/username.

**Comment by javaadpatel** [comment]
When you say setting the Id property of the user what do you mean?
I am currently setting it like this:
` var user = new IdentityUser
            {
                UserName = Guid.NewGuid().ToString(),
                Email = Guid.NewGuid().ToString(),
                Id = Guid.NewGuid().ToString()
            };

            await userManager.CreateAsync(user);`

but the records are written as in the above screenshot where the id then comes out as "user"

**Comment by FelschR** [comment]
The `partition` field in the DB will be set to the value from `user.Id` in your code sample above.

**Comment by FelschR** [comment]
Generally you will want to avoid cross partition queries.
I think indexing is only feasible if you limit your query to a single partition.
But I'm not entirely familiar with how indexing works in combination with partitioning.

**Comment by javaadpatel** [comment]
I see, okay i tried using FindUserByIdAsync(user.Id) and it works correctly. It was just confusing because the storage explorer shows that the documents id property is "user" so i was thinking that was what I would need to search for when using FindUserByIdAsync.

Are you doing something internally and thats why the explorers show a different id?

**Comment by FelschR** [comment]
This is because the library also works when using Cosmos DB without partitioning.
Without partitioning the `partition` field is not set and instead the `id` field is set to the user id.

**Comment by FelschR** [comment]
If instead you want to get multiple users in a single query you can also use `userManager.Users`.
It's an IQueryable so you can use LINQ to create your custom query.

**Comment by javaadpatel** [comment]
that makes sense, okay awesome, thank you for again for the help.
